[project]
name = "py-ad-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "pandas>=2.3.0",
    "requests>=2.32.4",
    "rich>=14.0.0",
    "tabulate>=0.9.0",
    "typer>=0.16.0",
]
